dataset_path: tests/data/bank_churners.csv
target_column: target
id_keys: ['clientnum']
valid_size: 0.2
random_state: 42
model_class: mlpipeline.model.LogisticRegressionModel
metrics:
  - ACCURACY
  - PRECISION
  - RECALL
  - F1_SCORE

numeric_config: configs/numeric.yaml
